### ISSUE TITLE
Cartage is missing #create_bundle_cache

### ISSUE THREAD

**Issue by jsutlovic** [KineticCafe/cartage#1]
Build fails on missing method `#create_bundle_cache`.

<img id="thegrab" src="http://new.tinygrab.com/a9ba49aee8e761fa3512d41c8523a9c7f588a2fe6b.png">

Error text:

```
Error:

    undefined local variable or method `create_bundle_cache' for #<Cartage:0x00000001c64278>

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/gems/cartage-1.0/lib/cartage.rb:298:in `install_vendor_bundle'

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/gems/cartage-1.0/lib/cartage.rb:131:in `pack'

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/gems/cartage-s3-1.0/lib/cartage/s3/command.rb:36:in `perform'

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/gems/cartage-1.0/lib/cartage/command.rb:39:in `execute'

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/gems/cmdparse-3.0.1/lib/cmdparse.rb:874:in `parse'

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/gems/cartage-1.0/lib/cartage.rb:451:in `run'

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/gems/cartage-1.0/bin/cartage:8:in `<top (required)>'

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/bin/cartage:23:in `load'

/home/semaphore/cartage/datahub_auth_rails/20150326175834/deps/ruby/2.1.0/bin/cartage:23:in `<main>'

Remote error in stage remote_build: SSH Command failed with status (2): 2
```

**Comment by halostatue** [comment]
This is actually KineticCafe/cartage-remote#1.

**Comment by halostatue** [comment]
The failure is in cartage, but cartage-remote is not properly failing.
